name: Deploy

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

env:
  APIURL: ${{ vars.APIURL }}
  PRINCIPAL_ID: ${{ vars.PRINCIPAL_ID }}
  REPLICATION_NAME: ${{ vars.REPLICATION_NAME }}  
  
jobs:
  deploy-npd:
    name: npd
    needs: set-env
    uses: AnoopHegde/pe-actions-deploy/.github/workflows/template-deploy-pe.yaml@main
    with:
      manifestPath: test-manifest.yaml
      environment: npd
    secrets: inherit
    

    
  
