name: Deploy

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read
  
jobs:
  npd-tokenize:
    name: npd-tokenize
    #id: tokenize
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Inject Variables
      id: tokenization
      uses: lindluni/actions-variable-groups@v2
      with:
        file: test-tokenized-manifest.yaml
        vars: |
          PRINCIPAL=test-principal
          REPLICATION_FACTOR=test-repl-factor

    - name: Replace Tokens
      uses: joshjohanning/replace-tokens@v1.4
      with:
        tokenPrefix: '{{'
        tokenSuffix: '}}'
        files: '["**/*-tokenized-manifest.yaml"]'

    - name: Override original manifest file
      run: |
        rm test-manifest.yaml
        mv test-tokenized-manifest.yaml test-manifest.yaml     
      

  deploy-npd:
    name: npd
    needs: npd-tokenize
    uses: AnoopHegde/pe-actions-deploy/.github/workflows/template-deploy-pe.yaml@main
    with:
      manifestPath: ${{ needs.npd-tokenize.outputs.manifestPath }}
      environment: npd
    secrets: inherit

    
  