name: Deploy

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

#env:
#  APIURL: ${{ vars.APIURL }}
#  PRINCIPAL_ID: ${{ vars.PRINCIPAL_ID }}
#  REPLICATION_NAME: ${{ vars.REPLICATION_NAME }}  
  
jobs:
  set-env:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    env:
      APIURL: https://api.example.com
      PRINCIPAL_ID: a378-c59f28847958-609f-4bd4-e203aa13
      REPLICATION_NAME: test-replication
    steps:
    - name: Set Environment Variables
      run: echo "APIURL=${APIURL}" >> $GITHUB_ENV && echo "PRINCIPAL_ID=${PRINCIPAL_ID}" >> $GITHUB_ENV && echo "REPLICATION_NAME=${REPLICATION_NAME}" >> $GITHUB_ENV
  
  deploy-npd:
    name: npd
    needs: set-env
    uses: AnoopHegde/pe-actions-deploy/.github/workflows/template-deploy-pe.yaml@main
    with:
      manifestPath: test-manifest.yaml
      environment: npd
    secrets: inherit
    

    
  
