name: Deploy

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

env:
  APIURL: ${{ vars.APIURL }}
  PRINCIPAL_ID: ${{ vars.PRINCIPAL_ID }}
  REPLICATION_NAME: ${{ vars.REPLICATION_NAME }}  
  
jobs:
  set-env:
     runs-on: ubuntu-latest
     env:
        APIURL: ${{ vars.APIURL }}
        PRINCIPAL_ID: ${{ vars.PRINCIPAL_ID }}
        REPLICATION_NAME: ${{ vars.REPLICATION_NAME }}
     steps:
      - uses: actions/checkout@v4   

  deploy-npd:
    name: npd
    needs: set-env
    uses: AnoopHegde/pe-actions-deploy/.github/workflows/template-deploy-pe.yaml@main
    #env:
    #  APIURL: ${{ env.APIURL }}
    #  PRINCIPAL_ID: ${{ env.PRINCIPAL_ID }}
    #  REPLICATION_NAME: ${{ env.REPLICATION_NAME }}
    with:
      manifestPath: test-manifest.yaml
      environment: npd
    secrets: inherit
    

    
  
