name: Deploy

on:
  push:
    branches: [ "main" ] 
    
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

#env:
#  APIURL: ${{ vars.APIURL }}
#  PRINCIPAL_ID: ${{ vars.PRINCIPAL_ID }}
#  REPLICATION_NAME: ${{ vars.REPLICATION_NAME }}  
  
jobs:
  set-env:
    runs-on: ubuntu-latest
    env:
      APIURL: https://api.example.com
      PRINCIPAL_ID: a378-c59f28847958-609f-4bd4-e203aa13
      REPLICATION_NAME: test-replication
    steps:
      - name: Export Environment Variables to File
        run: |
          env | grep -v '::' > $GITHUB_WORKSPACE/env_file.txt

  deploy-npd:
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using manifest and environment variables
        uses: AnoopHegde/pe-actions-deploy/.github/workflows/template-deploy-pe.yaml@main
        with:
          manifestPath: test-manifest.yaml
          environment: npd
          env_file: $GITHUB_WORKSPACE/env_file.txt
        secrets: inherit
    

    
  
